addSbtPlugin("com.typesafe.play" % "sbt-plugin"   % "2.5.10")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt" % "0.6.4")
resolvers += Resolver.bintrayIvyRepo("ovotech", "sbt-plugins")
addSbtPlugin("com.ovoenergy" % "sbt-comms-packaging" % "0.0.6")
addSbtPlugin("com.ovoenergy" % "sbt-credstash" % "0.0.7")
